# univention-google-apps translations.
# Copyright (C) 2016-2019 Univention GmbH
# This file is distributed under the same license as the univention-office365 package.
# Daniel Troeder <troeder@univention.de>, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: univention-google-apps\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2018-02-21 10:53+0100\n"
"PO-Revision-Date: 2016-04-07 12:57+0200\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: modules/univention/googleapps/handler.py:413
msgid ""
"API Access forbidden: Either the Admin Directory API has not been configured "
"in the developers-console or the scopes were not configured in the admin-"
"console. Please rerun the wizard."
msgstr ""
"API Zugriff verboten: Endweder wurde die Admin Directory API in der "
"developers-console nicht konfiguriert, oder die scopes wurden nicht in "
"der admin-console konfiguriert. Bitte starten Sie den Wizard erneut."

#: modules/univention/googleapps/auth.py:213
msgid "Error when modifying SAML service provider."
msgstr "Fehler beim Ändern des SAML Service Providers."

#: modules/univention/googleapps/auth.py:189
msgid "Error when writing credentials to disk."
msgstr "Fehler beim Schreiben von Zugangsdaten auf die Festplatte."

#: modules/univention/googleapps/auth.py:182
msgid "Missing data in credentials file."
msgstr "Fehlende Daten in Schlüsseldatei."

#: modules/univention/googleapps/auth.py:171
msgid "Please supply the name of a validated domain."
msgstr "Bitte geben Sie den Namen einer validierten Domäne an."

#: modules/univention/googleapps/auth.py:282
msgid ""
"SSL error. Please check your firewall/proxy settings and the servers system "
"time. Error: {}"
msgstr ""
"SSL Fehler. Bitte überprüfen Sie ihre Firewall-/Proxy-Einstellungen un die "
"Systemzeit des Servers. Fehler: {}"

#: modules/univention/googleapps/auth.py:279
msgid "Token could not be refreshed, you may try to connect again later."
msgstr ""
"Der Token konnte nicht erneuert werden. Es kann später erneut versucht "
"werden."
